#!/data/data/com.termux/files/usr/bin/bash

# Project N.O.M.A.D. — Native Termux Setup Script
# Replaces: docker-compose up / install_nomad.sh
#
# Run once after cloning the repository:
#   bash install/setup_termux.sh

set -e

RESET='\033[0m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'

NOMAD_HOME="${HOME}/nomad"
NOMAD_DATA="${NOMAD_HOME}/data"
NOMAD_RUN="${NOMAD_HOME}/run"
NOMAD_LOGS="${NOMAD_DATA}/logs"
NOMAD_ENV="${HOME}/.nomad_env"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ADMIN_DIR="${REPO_DIR}/admin"

info()    { echo -e "${GREEN}[N.O.M.A.D]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# ── Sanity checks ────────────────────────────────────────────────────────────

info "Checking environment..."

if [[ -z "${TERMUX_VERSION}" ]]; then
    warn "TERMUX_VERSION is not set. This script is designed for Termux on Android."
    warn "Continuing anyway — some paths may differ on other platforms."
fi

for cmd in node npm redis-server; do
    if ! command -v "$cmd" &>/dev/null; then
        error "Required command '${cmd}' not found. Run: pkg install nodejs redis"
    fi
done

# ── Directory setup ──────────────────────────────────────────────────────────

info "Creating N.O.M.A.D. directories..."
mkdir -p "${NOMAD_DATA}/logs" \
         "${NOMAD_DATA}/kb_uploads" \
         "${NOMAD_RUN}" \
         "${NOMAD_HOME}/redis"

# ── Generate secrets ─────────────────────────────────────────────────────────

generate_secret() {
    # Generates a 32-character alphanumeric secret using /dev/urandom
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
}

APP_KEY=$(generate_secret)

# ── Write environment file ───────────────────────────────────────────────────

info "Writing environment file to ${NOMAD_ENV}..."

cat > "${NOMAD_ENV}" <<EOF
# Project N.O.M.A.D. — Termux Environment
# Generated by setup_termux.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file then run start_termux.sh to apply changes.

export PORT=8080
export HOST=0.0.0.0
export LOG_LEVEL=info
export APP_KEY=${APP_KEY}
export NODE_ENV=production
export SESSION_DRIVER=cookie

export DB_FILENAME=${NOMAD_DATA}/nomad.db

export REDIS_HOST=127.0.0.1
export REDIS_PORT=6379

export NOMAD_STORAGE_PATH=${NOMAD_DATA}
export URL=http://127.0.0.1:8080
EOF

chmod 600 "${NOMAD_ENV}"
info "Environment file written."

# ── Start Redis ───────────────────────────────────────────────────────────────

info "Starting Redis..."
redis-server \
    --daemonize yes \
    --port 6379 \
    --bind 127.0.0.1 \
    --dir "${NOMAD_HOME}/redis" \
    --logfile "${NOMAD_LOGS}/redis.log" \
    --pidfile "${NOMAD_RUN}/redis.pid"

# Wait for Redis
info "Waiting for Redis to be ready..."
for i in $(seq 1 15); do
    if redis-cli ping 2>/dev/null | grep -q PONG; then
        break
    fi
    sleep 1
    if [[ $i -eq 15 ]]; then
        error "Redis did not start within 15 seconds. Check ${NOMAD_LOGS}/redis.log"
    fi
done
info "Redis is ready."

# ── Install Node.js dependencies ─────────────────────────────────────────────

info "Installing Node.js dependencies..."
cd "${ADMIN_DIR}"
npm ci --omit=dev 2>&1 | tee "${NOMAD_LOGS}/npm_install.log"

# Build the AdonisJS application if build output is not present
if [[ ! -f "${ADMIN_DIR}/build/bin/server.js" ]]; then
    info "Building AdonisJS application..."
    npm install --save-dev 2>/dev/null || true
    node ace build 2>&1 | tee "${NOMAD_LOGS}/build.log"
fi

BUILD_DIR="${ADMIN_DIR}/build"

# ── Run database migrations ───────────────────────────────────────────────────

info "Running database migrations..."
source "${NOMAD_ENV}"
node "${BUILD_DIR}/ace.js" migration:run --force 2>&1 | tee "${NOMAD_LOGS}/migrations.log"

info "Seeding the database..."
node "${BUILD_DIR}/ace.js" db:seed 2>&1 | tee "${NOMAD_LOGS}/seed.log"

# ── Start background workers ──────────────────────────────────────────────────

info "Starting background queue workers..."
nohup node "${BUILD_DIR}/ace.js" queue:work --all \
    >> "${NOMAD_LOGS}/nomad.log" \
    2>> "${NOMAD_LOGS}/nomad_err.log" &
echo $! > "${NOMAD_RUN}/nomad_worker.pid"

# ── Start the Command Center ──────────────────────────────────────────────────

info "Starting N.O.M.A.D. Command Center..."
nohup node "${BUILD_DIR}/bin/server.js" \
    >> "${NOMAD_LOGS}/nomad.log" \
    2>> "${NOMAD_LOGS}/nomad_err.log" &
NOMAD_PID=$!
echo "${NOMAD_PID}" > "${NOMAD_RUN}/nomad.pid"

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}║         Project N.O.M.A.D. is running!                  ║${RESET}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════╣${RESET}"
echo -e "${GREEN}║  Command Center:  http://127.0.0.1:8080                  ║${RESET}"
echo -e "${GREEN}║  Logs:            ${NOMAD_LOGS}/nomad.log   ║${RESET}"
echo -e "${GREEN}║  Stop:            bash install/stop_termux.sh            ║${RESET}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
